"""empty message

Revision ID: bf7eff08e01a
Revises: 9beb9715f203
Create Date: 2019-10-12 11:04:58.956778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf7eff08e01a'
down_revision = '9beb9715f203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finger_touch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stb_id', sa.String(), nullable=True),
    sa.Column('fingerprint_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finger_touch')
    # ### end Alembic commands ###
